server:
  port: 8080
databases:
  - user: admin
    password: admin
    host: localhost
    dbName: GoLang
    port: 5432
  - user: neverland
    password: neverland
    host: localhost
    dbName: neverland
    port: 5432
security:
  jwt:
    secret: abc123412
    expiration: 3600
redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
elasticsearch:
  host: localhost
  port: 9200
  user: ""
  password: ""
rabbitmq:
  host: localhost
  port: 5672
kafka:
  host: localhost
  port: 9092
  topic: test